### ISSUE TITLE
Wrong -verbose flag in CXXFLAGS

### ISSUE THREAD

**Issue by Enchufa2** [mpimd-csc/flexiblas#22]
Here: https://github.com/mpimd-csc/flexiblas/blob/c335f62590fd74c44255455507e8414bab23eb9a/tools/flexiblas-octave/src/Makefile#L14

Should be `--verbose`. Somehow this was filtered out, but apparently now [it's not](https://kojipkgs.fedoraproject.org/work/tasks/881/81450881/build.log). Very minor thing, no need to push another release for this. I'll just sed it out in the spec.

**Comment by grisuthedragon** [comment]
I changed it internally.

**Comment by grisuthedragon** [comment]
fixed in 3.1.3
