### ISSUE TITLE
Documentation on switching backends

### ISSUE THREAD

**Issue by dschwoerer** [mpimd-csc/flexiblas#23]
I don't use flexiblas that often, so that I always forget how to switch between the different backends as well as which are available.

It would be nice to add somewhere examples such as:
`FLEXIBLAS=openblas-openmp ./cmd`
and
`FLEXIBLAS=openblas-serial ./cmd`

Similarly, if there is some way to figure out what options are available, it would be great if that could be documented.

Concerning what documentation I am aware of:
`flexiblas --help`
`man flexiblas`
http://www.mpi-magdeburg.mpg.de/projects/flexiblas (including link to install instructions)
https://github.com/mpimd-csc/flexiblas
https://fedoraproject.org/wiki/Changes/FlexiBLAS_as_BLAS/LAPACK_manager

After double checking I did notice there is some documentation available:
https://github.com/mpimd-csc/flexiblas#usage-example - however that is very hard to find as it is hidden between installation instructions, which I do not need, as all I do is `dnf install bout++` or similar.

**Comment by grisuthedragon** [comment]
@dschwoerer 

Let me compress the key fact of your issue: Restructure the README such that the main information for the users is moved to a prominent place at the top? 

Furthermore, include the `dnf` way of installing it in the documentations?

**Comment by Enchufa2** [comment]
IMHO, adding a section with detailed examples in the man page would be very helpful for the users.

**Comment by dschwoerer** [comment]
@Enchufa2 It might make sense to add the existing ones for fedora to the fedora man page and mention with what packages they can be installed - that would be awesome :-)

**Comment by Enchufa2** [comment]
Yeap, I could create a downstream patch to add info specific to Fedora. @grisuthedragon What do you think? I would of course share it with you for your approval.

**Comment by grisuthedragon** [comment]
@dschwoerer I merge your PR. 

Regarding the manpage... I will rewrite it such that the main information are a bit more present.  

@Enchufa2 If it is only Fedora related information, it should be in a Downstream patch. If it is related to all users (or one can formulate it as "Note for Fedora users:....") I would like to integrate it in the upstream. Personally, I prefer that the distribution do not patch too much around.

**Comment by Enchufa2** [comment]
I understand. If you add generic examples to the man page, replicating some of the examples given in the README, then the downstream process could consist just in renaming the libraries to match the ones we use, as I do [here](https://src.fedoraproject.org/rpms/flexiblas/blob/rawhide/f/flexiblas.spec#_247) for the configuration files.

**Comment by Enchufa2** [comment]
I just saw the section added to the man page in the lastest push. LGTM, and no rename is required, so best of both worlds. Thanks! :)

**Comment by grisuthedragon** [comment]
I thought it was better to write it in a neutral way. 

Fixed in 3.1.3
