### ISSUE TITLE
No LAPACK API version specified

### ISSUE THREAD

**Issue by Enchufa2** [mpimd-csc/flexiblas#26]
LAPACK was [updated to v3.10.1](https://src.fedoraproject.org/rpms/lapack/c/6325e44b1e67985ec0bc6460101b0dfe0aaf5099?branch=rawhide) in Fedora rawhide and now FlexiBLAS is FTBFS with [the following error](https://kojipkgs.fedoraproject.org/work/tasks/8562/86238562/build.log):

```
-- Use external LAPACK from /usr/lib64/liblapack_pic.a with assumed API_VERSION 3.10.1
CMake Error at cmake/lapack.cmake:175 (MESSAGE):
  No LAPACK API version specified.  Use the LAPACK_API_VERSION varaiable.
```

Apart from the typo ("varaiable" ;-) ), it seems that the version was correctly assumed first but then ignored? Is this expected?

**Comment by grisuthedragon** [comment]
I will fix the typo and look at the reason why. Furthermore, I am on the way of importing LAPACK 3.10.1 since 2 subroutines (that normally noboby called from outside) are removed and two new useful ones are added. So the update will be there during the next days.

**Comment by tpopela** [comment]
Sorry to ask @grisuthedragon but is there any ETA? @Enchufa2 sadly the 3.10.1 update is part of Fedora 36 and FlexiBLAS FTBFS there are well and now it's blocking the flatpak-common module builds as well as the whole Fedora Flatpak 36 runtime builds/applications porting.

**Comment by grisuthedragon** [comment]
Hopefully this week....

**Comment by grisuthedragon** [comment]
Closed in 3.2.0

**Comment by Enchufa2** [comment]
Do I need to rebuild dependent packages?

**Comment by Enchufa2** [comment]
Built in F35, F36 and rawhide. Updates created:

- https://bodhi.fedoraproject.org/updates/FEDORA-2022-e1348190a6
- https://bodhi.fedoraproject.org/updates/FEDORA-2022-0e752f9a17
