### ISSUE TITLE
Strange annocheck reports

### ISSUE THREAD

**Issue by Enchufa2** [mpimd-csc/flexiblas#31]
[These reports](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/110355/testReport/(root)/tests/_annocheck/) keep bugging me, i.e. things like

```
Hardened: /usr/lib/flexiblas/libflexiblas_fallback_lapack.so: FAIL: glibcxx-assertions test because compiled without -D_GLIBCXX_ASSERTIONS (function: sgbbrd_) 
Hardened: /usr/lib/flexiblas/libflexiblas_fallback_lapack.so: info: For more information visit: https://sourceware.org/annobin/annobin.html/Test-glibcxx-assertions.html
```

Could this be a false positive due to the _magic_ you do to reroute the calls? Because the flag is present and passed to every single compilation unit, as you can see in [the logs](https://kojipkgs.fedoraproject.org//packages/flexiblas/3.2.0/4.fc35/data/logs/x86_64/build.log). So I don't know why annocheck thinks these symbols were compiled without it.

**Comment by grisuthedragon** [comment]
The documentation of the `glibcxx-assertations` test says:
```
  Problem:  Compiled C++ code might contain bugs that could have been detected and fixed
  Fix By:   Compile with -D_GLIBCXX_ASSERTIONS
  Waive If: Not compiling C++
  Waive If: Not using functions from libstdc++
```
So I think it is a false positive since at no point in FlexiBLAS base package a C++ compiler is used.  Only the Octave interface has to use it.

**Comment by Enchufa2** [comment]
[facepalm] Right, thanks for taking a look.
