### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Enchufa2** [mpimd-csc/flexiblas#43]
I'm updating the Fedora package and I see [failures in several architectures](https://koji.fedoraproject.org/koji/taskinfo?taskID=111538276):

- [i686 log](https://kojipkgs.fedoraproject.org//work/tasks/8357/111538357/build.log)
- [s390x log](https://kojipkgs.fedoraproject.org//work/tasks/8361/111538361/build.log)

```
99% tests passed, 1 tests failed out of 119
Total Test time (real) = 168.38 sec
The following tests FAILED:
	 70 - LAPACK-xdmdeigtstd_ddmd_in (Failed)
Errors while running CTest
```

- [x86_64 log](https://kojipkgs.fedoraproject.org//work/tasks/8358/111538358/build.log)

```
99% tests passed, 1 tests failed out of 119
Total Test time (real) = 181.97 sec
The following tests FAILED:
	119 - LAPACK_Test_Summary (Failed)
Errors while running CTest
```

aarch64 succeeded and ppc64le is still running. This is with LAPACK 3.12.0 in rawhide.

**Comment by grisuthedragon** [comment]
The failures regarding dmd may result from a buggy LAPACK 3.12.0 since there are some bugs regarding the DMD codes and their tests. For this reason, I integrated Reference-Lapack/lapack#959 in FlexiBLAS as well. In contrast to LAPACK 3.12.0 build with CMAKE, the DMD tests are enabled. 

For the summary, could you run the tests with `--output-on-failure` flag set, when calling `ctest`?

**Comment by Enchufa2** [comment]
I see. I'll postpone activating v3.12.0 in rawhide for now then.

> For the summary, could you run the tests with `--output-on-failure` flag set, when calling `ctest`?

Thanks for the tip! I'll activate this from now on. Here are the logs with this flag: [1](https://kojipkgs.fedoraproject.org//work/tasks/4210/111544210/build.log), [2](https://kojipkgs.fedoraproject.org//work/tasks/4211/111544211/build.log).

**Comment by Enchufa2** [comment]
[All good now](https://koji.fedoraproject.org/koji/taskinfo?taskID=111545060), thanks!
