### ISSUE TITLE
heap-arrays argument is passed wrong on Windows with Intel compiler

### ISSUE THREAD

**Issue by julianh-siemens** [mpimd-csc/flexiblas#53]
https://github.com/mpimd-csc/flexiblas/blob/ff45f246a0b4b489f27ec88e3d114e664ab49f55/libcscutils/CMakeModules/FortranCompilerSettings.cmake#L116

A colon is missing on Windows with the Intel compiler.

Intel Fortran compiler reference:
https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2024-1/heap-arrays.html

**Comment by grisuthedragon** [comment]
Fixed in the dev sources. But be aware, that FlexiBLAS is not developed on Windows, nor tested on this platform. Furthermore, no support will be provided.
