### ISSUE TITLE
cblas scnrm2 typo

### ISSUE THREAD

**Issue by julianh-siemens** [mpimd-csc/flexiblas#54]
https://github.com/mpimd-csc/flexiblas/blob/ff45f246a0b4b489f27ec88e3d114e664ab49f55/src/cblas_interface/cblas_scnrm2.c#L68

This appears to be a typo and should be `FC_GLOBAL(scnrm2,SCNRM2)`.

**Comment by grisuthedragon** [comment]
Yes this is a typo, but in almost all current BLAS implementations, this will not cause any problems since the uppercase Fortran names are not used by any current compiler.

**Comment by grisuthedragon** [comment]
Closed by 28ef5756fab172854342af67d43fcf35f5dc4f5a
