### ISSUE TITLE
Consistent indentation

### ISSUE THREAD

**Issue by julianh-siemens** [mpimd-csc/flexiblas#55]
The source code and CMakeLists files have mixed tabs/spaces in a lot of places. This makes the code very hard to read.
It would be nice if one indentation style (I don't care which one) could be used across the whole project.

**Comment by grisuthedragon** [comment]
I'll search for an automated way to keep the files in style.

**Comment by grisuthedragon** [comment]
Closed by 28ef5756fab172854342af67d43fcf35f5dc4f5a
