### ISSUE TITLE
Typos in logging output

### ISSUE THREAD

**Issue by julianh-siemens** [mpimd-csc/flexiblas#56]
Some minor typos in logging output:

https://github.com/mpimd-csc/flexiblas/blob/ff45f246a0b4b489f27ec88e3d114e664ab49f55/src/flexiblas.c#L213
Missing newline at the end of the string.

https://github.com/mpimd-csc/flexiblas/blob/ff45f246a0b4b489f27ec88e3d114e664ab49f55/src/flexiblas.c#L300
Should probably be: "does not seem to **be** a shared library. Search inside the FlexiBLAS configuration..**.**"

**Comment by grisuthedragon** [comment]
Closed by 28ef5756fab172854342af67d43fcf35f5dc4f5a
