### ISSUE TITLE
Wrong return type

### ISSUE THREAD

**Issue by Enchufa2** [mpimd-csc/flexiblas#6]
I believe this

https://github.com/mpimd-csc/flexiblas/blob/2a6fd3f591c206cff72345fd2902216bb95f508f/src/flexiblas_api_standalone.c#L371-L374

should return `void` instead?

**Comment by grisuthedragon** [comment]
Yes it is a bug. It will be fixed in the next version.

**Comment by grisuthedragon** [comment]
Fixed in 3.0.4
